# Generated by Django 4.2.5 on 2023-09-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("UR", "Urgent"),
                    ("HG", "Height"),
                    ("MD", "Medium"),
                    ("LW", "Low"),
                ],
                default="MD",
                max_length=2,
            ),
        ),
    ]
