# Generated by Django 4.2.5 on 2023-10-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_alter_worker_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="position",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="tasktype",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="worker",
            options={"ordering": ("username",)},
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("Urgent", "Urgent"),
                    ("Height", "Height"),
                    ("Medium", "Medium"),
                    ("Low", "Low"),
                ],
                default="Medium",
                max_length=64,
            ),
        ),
    ]
